build:

    environment:
        php:
            version: "5.5.25" # Common versions: 5.4.28, 5.5.25, or hhvm
            ini:
                'date.timezone': 'UTC'
        redis: false

    dependencies:

        before:
            - composer install --prefer-dist -o
            - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b master
            - cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && sed -i '$ a \\n[Phalcon]\nextension=phalcon.so\n'  /home/scrutinizer/.phpenv/versions/5.5.25/etc/php.ini
            - cd /home/scrutinizer/build

filter:
    paths: [src/*]
    excluded_paths: [build/*, examples/*, phpunit/*, vendor/*]

tools:
    php_sim: true
    php_pdepend:
        enabled: true
        command: pdepend
        suffixes:
            - php
        excluded_dirs:
            - build
            - examples
            - phpunit
            - vendor

    php_code_coverage: true

    php_analyzer:
        enabled: true
        filter:
            excluded_paths: [build/*, examples/*, phpunit/*, vendor/*]
        extensions:
            - php

    sensiolabs_security_checker: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        extensions:
            - php
        filter:
           excluded_paths: [build/*, examples/*, phpunit/*, vendor/*]

    php_cs_fixer:
        enabled: true
        extensions:
            - php
        config:
            level: all

checks:
    php:
        code_rating: true
        duplication: false
        verify_property_names: true
        verify_argument_usable_as_reference: true
        verify_access_scope_valid: true
        variable_existence: true
        use_statement_alias_conflict: true
        symfony_request_injection: true
        sql_injection_vulnerabilities: true
        security_vulnerabilities: true
        require_php_tag_first: true
        precedence_in_conditions: true
        precedence_mistakes: true
        parameter_non_unique: true
        no_eval: true
        no_non_implemented_abstract_methods: true
        no_duplicate_arguments: true
        missing_arguments: true
        instanceof_class_exists: true
        foreach_traversable: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        catch_class_exists: true
        argument_type_checks: true
        assignment_of_null_return: true
        useless_calls: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        too_many_arguments: true
        switch_fallthrough_commented: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        php5_style_constructor: true
        phpunit_assertions: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_unnecessary_function_call_in_for_loop: true
        no_unnecessary_final_modifier: true
        no_property_on_interface: true
        method_calls_on_non_object: true
        foreach_usable_as_reference: true
        fix_use_statements:
            remove_unused: false
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        encourage_shallow_comparison: true
        deprecated_code_usage: true
        avoid_unnecessary_concatenation: true
        avoid_corrupting_byteorder_marks: true
        avoid_conflicting_incrementers: true
        unreachable_code: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        space_after_cast: true
        single_namespace_per_use: true
        simplify_boolean_return: true
        side_effects_or_types: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_braces_around_control_structures: true
        remove_trailing_whitespace: true
        remove_php_closing_tag: true
        remove_extra_empty_lines: true
        psr2_control_structure_declaration: true
        psr2_class_declaration: true
        properties_in_camelcaps: true
        prefer_unix_line_ending: true
        no_trait_type_hints: true
        no_underscore_prefix_in_methods: true
        no_underscore_prefix_in_properties: true
        no_short_variable_names:
            minimum: '1'
        no_short_open_tag: true
        no_short_method_names:
            minimum: '3'
        no_mixed_inline_html: true
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        no_global_keyword: true
        no_exit: true
        no_empty_statements: true
        no_debug_code: true
        no_commented_out_code: true
        line_length:
            max_length: '200'
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        classes_in_camel_caps: true
        avoid_useless_overridden_methods: true
        avoid_todo_comments: true
        avoid_tab_indentation: true
        avoid_superglobals: true
        avoid_perl_style_comments: true
        avoid_entity_manager_injection: true
        prefer_sapi_constant: true
        more_specific_types_in_doc_comments: true
        avoid_usage_of_logical_operators: true